name:                meme
version:             0.1.0.0
github:              "dreamsmasher/meme"
license:             BSD3
author:              "Norman Liu"
copyright:           "2020 Norman Liu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            meme: a monadic scheme implementation
# category:            Languages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dreamsmasher/meme#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.12 && < 3.1.18
- mtl >=2.2.1 && < 2.2.3
- transformers > 0.5.6 && < 0.5.7
- haskeline >= 0.7.5 && < 0.8.1

library:
  source-dirs: src

default-extensions:
    - LambdaCase

executables:
  meme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - meme
  
tests:
  meme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meme
